### ISSUE TITLE
pecs 中关于Domain-DomainName 字段没有说明

### ISSUE THREAD

**Issue by zmofei** [alibaba/funcraft#1014]
在文档中 https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#%E5%B1%9E%E6%80%A7-2 没有看到 Dmaoin/DomainName 的说明，该字段还未发放么？

另外： 如果一个fc绑定了多个 DomainName 如何通过 `template` 声明:

```
  Domain:
    Type: 'Aliyun::Serverless::CustomDomain'
    Properties:
      DomainName: "serverA.test.com"
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/*":
            ServiceName: serverA
            FunctionName: serverAFn1
          "/api/*":
            ServiceName: serverB
            FunctionName: serverBFn1
```

如上如果需要增加一个 `serverB.test.com`的`DomainName`有方法么？
