### ISSUE TITLE
执行fun local start似乎没有执行Funfile里面的命令？

### ISSUE THREAD

**Issue by liuqian1996** [alibaba/funcraft#1106]
版本
fun：3.6.21
docker：windows，Docker version 20.10.5, build 55c4c88

描述
使用`fun local start`的时候，提示模块不存在，查看docker日志，并没有执行Funfile文件里面的命令

**template.yml**
```yml
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  fastify-words: # service name
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is a fastify server
    words: # function name
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: app.handler
        Runtime: nodejs12
        CodeUri: ./dist
        MemorySize: 1024
        InstanceConcurrency: 5
        Timeout: 120
        EnvironmentVariables:
          ENV_TEST: 'Env_Test'

      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['GET', 'POST', 'PUT']
  Domain:
    Type: Aliyun::Serverless::CustomDomain
    Properties:
      DomainName: Auto
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/*":
            ServiceName: fastify-words
            FunctionName: words
```

**Funfile**
```Dockerfile
RUNTIME nodejs12
RUN npm install
```

**文件结构**

![image](https://user-images.githubusercontent.com/11707934/114641371-94fd7280-9d04-11eb-8eae-809d565d7496.png)

**Docker日志**

![image](https://user-images.githubusercontent.com/11707934/114641531-e0b01c00-9d04-11eb-95a1-ee4123286de9.png)

**Docker里文件结构**

![image](https://user-images.githubusercontent.com/11707934/114641581-f6254600-9d04-11eb-85f8-08cdc261933c.png)

期待

能够正常执行
