### ISSUE TITLE
不能更新自定义域名

### ISSUE THREAD

**Issue by wsw0108** [alibaba/funcraft#1113]
通过在template.yml里设置自定义域名。

最初是用的`DomainName: Auto`，现在想改为自己设置绑定的CNAME，如`DomainName: api.example.com`。

在`fun deplly`时，返回如下错误：
`Update to properties DomainName of Domain (ALIYUN::FC::CustomDomain) is not supported., URL: http://ros.aliyuncs.com/`

**Comment by wsw0108** [comment]
```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Domain:
    Type: 'Aliyun::Serverless::CustomDomain'
    Properties:
      DomainName: Auto
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/*":
            ServiceName: s1
            FunctionName: f1
```
