### ISSUE TITLE
fun deploy put custom-domains return 400

### ISSUE THREAD

**Issue by ldbmcs** [alibaba/funcraft#1117]
版本：mac v3.6.22
问题：

设置了customDomain后，fun deploy 报错，信息如下：
![image](https://user-images.githubusercontent.com/14944966/118577615-4fc5d800-b7bd-11eb-94a2-929da44b466e.png)
域名已解析，能访问。

template.yml

```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  fundAuthStatic: # service name
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is FC service
    fundAuthStatic: # function name
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        CodeUri: ./
        MemorySize: 1024
        InstanceConcurrency: 5
        Timeout: 120
        
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['GET', 'POST', 'PUT']
  test.ldbmcs.com:
    Type: Aliyun::Serverless::CustomDomain
    Properties:
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/":
            ServiceName: fundAuthStatic
            FunctionName: fundAuthStatic
 ```

期待：

正常部署
