### ISSUE TITLE
fun ERR! additional Resources/jfinal-4.9-spring-boot-2.3.0: Unexpected property jfinal-4.9-spring-boot-2.3.0

### ISSUE THREAD

**Issue by litongjava** [alibaba/funcraft#1126]
将spring-boot应用发布到计算函数时出现上面的错误,发布的过程如下
spring-boot应用开源地址
```
https://gitee.com/litongjava_admin/jfinal-4.9-spring-boot-2.3.0
```
使用mvn package命令打包,执行成功
```
cd jfinal-4.9-spring-boot-2.3.0
mvn pakcage
```
执行fun deploy -y发布时出现下面的错误
```
E:\dev_workspace\java\project-litongjava\jfinal-4.9-spring-boot-2.3.0>fun deploy -y
current folder is not a fun project.
Generating template.yml...
Generate Fun project successfully!


========= Fun will use 'fun deploy' to deploy your application to Function Compute! =========
fun ERR! additional Resources/jfinal-4.9-spring-boot-2.3.0: Unexpected property jfinal-4.9-spring-boot-2.3.0
fun ERR! template is not valid

E:\dev_workspace\java\project-litongjava\jfinal-4.9-spring-boot-2.3.0>cat template.yml
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  jfinal-4.9-spring-boot-2.3.0: # service name
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is FC service
    jfinal-4.9-spring-boot-2.3.0: # function name
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        CodeUri: ./
        MemorySize: 1024
        InstanceConcurrency: 5
        Timeout: 120

      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['GET', 'POST', 'PUT']
  Domain:
    Type: Aliyun::Serverless::CustomDomain
    Properties:
      DomainName: Auto
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/*":
            ServiceName: jfinal-4.9-spring-boot-2.3.0
            FunctionName: jfinal-4.9-spring-boot-2.3.0

E:\dev_workspace\java\project-litongjava\jfinal-4.9-spring-boot-2.3.0>
```
猜测Resources/jfinal-4.9-spring-boot-2.3.0中的jfinal-4.9-spring-boot-2.3.0是不符合funcraft的命名规则,但是jfinal-4.9-spring-boot-2.3.0的命名规则在时间项目中很常用
