### ISSUE TITLE
template.yml 中资源命名冲突问题

### ISSUE THREAD

**Issue by badoths** [alibaba/funcraft#202]
## 问题
template.yml 里 Resources 描述的不同资源，如果拥有同样名字会导致命名冲突。目前解决办法是，给资源名字加上前缀或后缀以示区别。但是不同资源本来就拥有自己独立的命名空间，加前后缀的方式，会破坏这种独立性。
## 例子
```yaml
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  A:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      ...
  A: # 冲突
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        ...
```
上面的第二个同名的 A，会冲突，导致无法创建资源。
## 提议
对 yaml 的语法不熟，不知能不能只是在 template 里面加前后缀，实际创建资源时自动把前后缀去掉。譬如上文的第二个 `A:` 可以改为 `api A:`
