### ISSUE TITLE
fun deploy 打包时直接闪退的问题

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#351]
使用如下的 fun.yml 可以重现问题：
```
runtime: python2.7
tasks:
  - pip: xmltodict
    local: true
  - pip: alipay-sdk-python
    local: true
  - pip: redis
    local: true
```

推测是 js zip 的 bug
