### ISSUE TITLE
fun 本地调试支持 custom runtime 吗

### ISSUE THREAD

**Issue by joseelin** [alibaba/funcraft#416]
fun 本地调试支持 custom runtime 吗
```shell
# 版本
fun --version
2.16.5
```
```yaml
//配置
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  local-http-test:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'local invoke demo'
    golang:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        CodeUri: './bootstrap'
        Description: 'http trigger demo with nodejs8!'
        Runtime: custom //运行环境
        Handler: index.handler
      Events:
        http-test:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['GET', 'POST', 'PUT', 'DELETE', 'HEAD']
```
```txt
# 输出
function compute app listening on port 8000!
invalid runtime name custom
```
