### ISSUE TITLE
自动生成的 Dockerfile 问题

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#448]
今天刚用上 fun 3.0.0，fun install 运行自动生成的 dockerfile 有问题

这是我的 fun.yml

```yaml
runtime: python3
tasks:
  - pip: aiohttp
    local: true
  - pip: beautifulsoup4
    local: true
  - pip: lxml
    local: true
  - pip: uvloop
    local: true
```

它自动生成的 Dockerfile 是这样的

```dockerfile
FROM aliyunfc/runtime-python3.6:build-1.6.2
COPY . /code
WORKDIR /code
RUN fun-install pip install aiohttp
RUN fun-install pip install beautifulsoup4
RUN fun-install pip install lxml
RUN fun-install pip install uvloop
```

我想任何使用过Docker的人都知道，尽量把安装环境和安装依赖这一步放在前面才能充分利用缓存机制。因为项目代码是频繁更改的，而依赖的变动很少。

这个自动生成的 Dockerfile 是不是考虑优化一下？
