### ISSUE TITLE
Github Action 支持

### ISSUE THREAD

**Issue by htynkn** [alibaba/funcraft#474]
官方有提供Github Action支持的计划吗？
比如发布函数这些？

类似的Azure有：https://github.com/Azure/actions

**Comment by gohopo** [comment]
可以按下面的步骤使用fun部署.
先要安装node
```
- name: setup node
      uses: actions/setup-node@master
```
再安装fun
```
- name: setup fun
      run: npm i -g @alicloud/fun
```
再部署,secrets是你工程设置中的环境变量
```
    - name: deploy
      run: |
        mv ./Orion/bin/publish/Orion ./Orion/bin/publish/bootstrap
        fun deploy -v
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: cn-hangzhou
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
```
