### ISSUE TITLE
The policy has already been attached to the role.

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#507]
```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  libreoffice:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'libreoffice example'
      NasConfig: Auto
      Policies:
        - AliyunOssFullAccess
    word2pdf-nodejs8:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs8
        Timeout: 60
        MemorySize: 640
        CodeUri: './nodejs8'
        EnvironmentVariables:
          LD_LIBRARY_PATH: /code/.fun/root/usr/lib/x86_64-linux-gnu/nss
    word2pdf-python3:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: python3
        Timeout: 60
        MemorySize: 1024
        CodeUri: './python3'
        EnvironmentVariables:
          LD_LIBRARY_PATH: /code/.fun/root/usr/lib/x86_64-linux-gnu/nss
          OSS_REGION: cn-shanghai
          OSS_BUCKET: vangie-test
```

```
╰─➜  ../../fun/bin/fun.js deploy word2pdf-python3
using template: .fun/build/artifacts/template.yml
using region: cn-hongkong
using accountId: ***********4733
using accessKeyId: ***********EUz3
using timeout: 600

Waiting for service libreoffice to be deployed...
        make sure role 'aliyunfcgeneratedrole-cn-hongkong-libreoffice' is exist
        role 'aliyunfcgeneratedrole-cn-hongkong-libreoffice' is already exist
        attaching policies AliyunOssFullAccess to role: aliyunfcgeneratedrole-cn-hongkong-libreoffice
retry 1 times
retry 2 times
retry 3 times
retry 4 times
The policy has already been attached to the role.
```

把 AliyunOssFullAccess 改成 AliyunOSSFullAccess  就 OK 了。
