### ISSUE TITLE
PathConfig 支持 Qualifier 字段

### ISSUE THREAD

**Issue by zephyrpersonal** [alibaba/funcraft#542]
在阿里云管理后提工单后了解到FC API已经支持PathConfig内添加Qualifier字段

这个功能对于使用funcraft发布自定义域名还是非常有用的

不知道何时能实装，谢谢

**Comment by tanhe123** [comment]
这里的 PathConfig 指的是？方便具体描述下使用场景吗？

**Comment by zephyrpersonal** [comment]
@tanhe123 

使用场景是：

我们团队在yaml文件内使用了 `Aliyun::Serverless::CustomDomain` 自定义域名

根据[规范](https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#aliyunserverlesscustomdomain)配置如下

```yaml
custom-domain.com:
    Type: "Aliyun::Serverless::CustomDomain"
    Properties:
      Protocol: HTTP
      RouteConfig:
        routes:
          "/helloworld":
            ServiceName: helloworld_service
            FunctionName: helloworld_func
```

现在希望能够增加一个Qualifier属性，
这样可以直接在deploy指定域名路由对应的函数版本

e.g.

```yaml
custom-domain.com:
    Type: "Aliyun::Serverless::CustomDomain"
    Properties:
      Protocol: HTTP
      RouteConfig:
        routes:
          "/helloworld":
            ServiceName: helloworld_service
            FunctionName: helloworld_func
            Qualifier: Prod # 新增别名支持
```

根据售后工程师的反馈现在函数计算管理api已经支持在新建/更新自定义域名时指定Qualifier。
所以不知道fun何时能够实装这个功能？

期望：新字段能够通过fun validate的校验。
