### ISSUE TITLE
使用 fun nas 时，nas 的配置没有改动，但是还是每次都更新 _FUN_NAS_ service 的配置

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#566]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/4676235/67832680-5e866480-fb1d-11e9-99f6-2c4a27bde4a4.png">

```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  puppeteer:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'helloworld'
      Policies:
        - AliyunOSSFullAccess
      NasConfig: Auto
```
