### ISSUE TITLE
NasConfig: Auto 支持指定 UserId、GroupId

### ISSUE THREAD

**Issue by coco-super** [alibaba/funcraft#633]

**Comment by coco-super** [comment]
![image](https://user-images.githubusercontent.com/48934955/69798290-05891980-120c-11ea-9a2c-9b6a31a545cd.png)

**Comment by vangie** [comment]
NASConfig: Auto 理解成

```
NASConfig:
  Auto: true
```
的省略写法会保护更好些？

这样上面的例子就可以写成

```
NASConfig:
  Auto: true
  UserId: 33
  GroupId: 33
```
