### ISSUE TITLE
fun install 怎么安装自己的自有库的依赖包

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#659]
fun install 怎么安装自己的自有库的依赖包 pip install testfun --index-url https://testpip.   或npm install  --registry=https://registry.npm.taobao.org

问题来自于工单 2HB8Y0X

**Comment by iwillwen** [comment]
我的需求是需要安装 Python 模块`ta-lib`，该模块依赖需要自行编译的`ta-lib`原生库。

我目前的做法是先将`ta-lib`原生库的源代码放到代码文件夹里，然后通过一个shell task进行编译，然后再通过 fun-install 安装 Python 模块。

```shell
# deps/ta-lib/install.sh
cd deps

cd ta-lib
./configure --prefix=/code/.fun/usr
make
make install
```

```yaml
- shell: ./deps/ta-lib/install
  local: true
- pip: ta-lib
  local: true
```

第一个 shell 任务是可以成功编译完成的，但到了第二个 pip 任务时，依然会报无法找到该原生库。
