### ISSUE TITLE
关于 CustomDomain Spec 文档表述问题

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#753]
1.  routes 建议改成 Routes，目前代码兼容两种表述，但是建议用户使用更规范的 Routes
```
abc.com: # domain name
  Type: 'Aliyun::Serverless::CustomDomain'
  Properties:
    Protocol: HTTP
    RouteConfig:
      routes: 
        '/a':
          ServiceName: serviceA
          FunctionName: functionA
        '/b':
          ServiceName: serviceB
          FunctionName: functionB
```
2. 
![image](https://user-images.githubusercontent.com/1388582/73724761-02a82900-4767-11ea-8aac-fc4bba6165ff.png)
RouteConfig 的类型不是 PathConfig 数组，这里表述不对。

3. 缩进问题

![image](https://user-images.githubusercontent.com/1388582/73724854-3aaf6c00-4767-11ea-921e-fa53462d4d27.png)
