### ISSUE TITLE
当绑定了 CustomDomain 时 Http Trigger 自动下载的警告应该去掉

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#754]
```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  puppeteer:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: helloworld
      # NasConfig: Auto
    html2png:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Initializer: index.initializer
        Runtime: nodejs8
        CodeUri: ./
        MemorySize: 768
        Timeout: 360
        InitializationTimeout: 60
        EnvironmentVariables:
          LD_LIBRARY_PATH: >-
            /mnt/auto/root/usr/lib:/mnt/auto/root/usr/lib/x86_64-linux-gnu:/mnt/auto/root/lib/x86_64-linux-gnu:/mnt/auto/root/usr/lib64
          NODE_PATH: '/usr/local/lib/node_modules:/mnt/auto/node_modules'
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods:
              - GET
  ppp.codelife.me:
    Type: Aliyun::Serverless::CustomDomain
    Properties:
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/":
            ServiceName: puppeteer
            FunctionName: html2png
```

```
╰─➜  fun deploy
using template: template.yml
using region: cn-hongkong
using accountId: ***********3743
using accessKeyId: ***********Ptgk
using timeout: 600

Waiting for service puppeteer to be deployed...
        Waiting for function html2png to be deployed...
                Waiting for packaging function html2png code...
                The function html2png has been packaged. A total of 6 files files were compressed and the final size was 2.13 KB
                Waiting for HTTP trigger httpTrigger to be deployed...
                triggerName: httpTrigger
                methods: [ 'GET' ]
                url: https://1986114430573743.cn-hongkong.fc.aliyuncs.com/2016-08-15/proxy/puppeteer/html2png/
                Http Trigger will forcefully add a 'Content-Disposition: attachment' field to the response header, which cannot be overwritten 
                and will cause the response to be downloaded as an attachment in the browser. This issue can be avoided by using CustomDomain.

                trigger httpTrigger deploy success
        function html2png deploy success
service puppeteer deploy success

Waiting for custom domain ppp.codelife.me to be deployed...
custom domain ppp.codelife.me deploy success
```
