### ISSUE TITLE
fun local 不支持 python redis 库

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#770]
重现方法

template.yml 文件
```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  redis: 
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is FC service for redis
    python:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: 'index.handler'
        Runtime: python3
        Timeout: 10
        MemorySize: 128
        CodeUri: ./
```

requirements.txt
```
redis
```

index.py
```
import os,sys
print(sys.path)
import redis

def handler(event, context):
    return 'hello world'
```

执行命令
```
fun install 
# 或者
fun build
```

fun local invoke 报错，部署到远端应该一样会报错的

```
FC Invoke Start RequestId: 1ebcb234-1b1e-48b7-b8ad-d1f55cc7e0c0
['/code', '/var/fc/runtime/python3/src', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages']
2020-02-11T10:26:25.781Z 1ebcb234-1b1e-48b7-b8ad-d1f55cc7e0c0 [ERROR] {'errorMessage': "Unable to import module 'index'", 'errorType': 'ImportError', 'stackTrace': ["ModuleNotFoundError: No module named 'redis'"]}
FC Invoke End RequestId: 1ebcb234-1b1e-48b7-b8ad-d1f55cc7e0c0
{
    "errorMessage": "Unable to import module 'index'",
    "errorType": "ImportError",
    "stackTrace": [
        "ModuleNotFoundError: No module named 'redis'"
    ]
}
```
