### ISSUE TITLE
使用ros部署api失败

### ISSUE THREAD

**Issue by yoogr** [alibaba/funcraft#861]
Fun: 3.6.8

template: 

```yaml
CoreGroup: 
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        '/api/login': 
          post: 
            x-aliyun-apigateway-api-name: login
            x-aliyun-apigateway-fc: 
              arn: acs:fc:::services/car/functions/core
              timeout: 3000
```

使用`fun deploy`能部署成功，使用`fun deploy --use-ros`提示错误:
The role arn acs:fc:::services/car/functions/core is not correct: : , URL: http://ros.aliyuncs.com/
