### ISSUE TITLE
使用ros部署api报错

### ISSUE THREAD

**Issue by yoogr** [alibaba/funcraft#862]
fun: 3.6.8

template.yaml: 

```yaml
CoreGroup: 
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        '/api/login': 
          post: 
            x-aliyun-apigateway-api-name: login
            x-aliyun-apigateway-fc: 
              arn: acs:fc:::services/car/functions/core
              timeout: 3000
```

使用`fun deploy`能正常部署成功，使用`fun deploy --use-ros --stack-name xxx`报错: 
deploying by ROS, The Stack name is xxx
The role arn acs:fc:::services/car/functions/core is not correct: : , URL: http://ros.aliyuncs.com/

**Comment by coco-super** [comment]
@yoogr 由于 ROS 部署，要求资源必须“云化”。也就是没办法直接使用本地的代码资源。必须先通过 fun package 命令将资源上传到 oss。我这边测试是没问题的：
```
CoreGroup:
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        /api/login:
          post:
            x-aliyun-apigateway-api-name: login
            x-aliyun-apigateway-fc:
              arn: 'acs:fc:::services/${fc.Arn}/functions/${apigateway.Arn}/'
              timeout: 3000
```
步骤如下： 
1. fun deploy 
2. fun package -b oss-bucket
3. fun deploy --use-ros --stack-name api
