### ISSUE TITLE
Fun deploy NODE_PATH 环境变量不正确

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#879]
该问题会导致 nas 上的 uuid 库引用不到。

![image](https://user-images.githubusercontent.com/1388582/79835016-942b4c80-83e0-11ea-828c-e04b7317e18e.png)

改成如下以后就正常了。
![image](https://user-images.githubusercontent.com/1388582/79835035-98f00080-83e0-11ea-8600-8305fd9b2f28.png)

发现问题的 fun 版本 3.6.9。

出现问题的 template.yml 的内容如下

```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  uuid-example:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is FC service
      Role: 'acs:ram::1986114430573743:role/fc-public-test'
      NasConfig: Auto
    uuid-example2:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs10
        Timeout: 120
        CodeUri: ./
        MemorySize: 1024
        EnvironmentVariables:
          NODE_PATH: '/mnt/auto/node_modules:/usr/local/lib/node_modules'
```

测试代码

```
'use strict';
const uuid = require('uuid');


module.exports.handler = function(event, context, callback) {
  console.log(uuid.v1());
  callback(null, uuid.v1());
}
```

.nas.yml

```
nasMappings:
  uuid-example:
    - localNasDir: node_modules
      remoteNasDir: /mnt/auto/node_modules
```
