### ISSUE TITLE
egg项目fun deploy -y后运行404

### ISSUE THREAD

**Issue by Hufe921** [alibaba/funcraft#887]
使用方式：
```
1. npm init egg --type=simple
2. npm i
3.npm run dev
4.fun deploy -y
```
生成的bootstrap：
```
#!/usr/bin/env bash
export PORT=9000
export EGG_SERVER_ENV=prod
npx --no-install egg-scripts start --workers=1
```
生成的yml
```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  test-egg-fc: # service name
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is FC service
    test-egg-fc: # function name
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        CodeUri: ./
        MemorySize: 1024
        InstanceConcurrency: 5
        Timeout: 120
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['GET', 'POST', 'PUT']
  Domain:
    Type: Aliyun::Serverless::CustomDomain
    Properties:
      DomainName: Auto
      Protocol: HTTP
      RouteConfig:
        Routes:
          "/*":
            ServiceName: test-egg-fc
            FunctionName: test-egg-fc
  ```
后直接在控制台运行项目
报：404

egg生成的代码完全没改，路由：
```
module.exports = app => {
  const { router, controller } = app;
  router.get('/', controller.home.index);
};
```

操作方式和：https://help.aliyun.com/document_detail/162578.html?spm=a2c4g.11186623.6.741.60b265c9lISOSi 一模一样
