### ISSUE TITLE
fun deploy 部署超过 50M 后配置 nas 无效

### ISSUE THREAD

**Issue by hongfs** [alibaba/funcraft#989]
系统：win10
fun 版本：3.6.14

`template.yml`

```yml
Resources:
  demo: # service name
    Type: 'Aliyun::Serverless::Service'
    Properties:
      NasConfig: Auto
```

```shell
$ fun deploy -y
...
using 'NasConfig: Auto', Fun will try to generate related nas file system automatically
                nas file system already generated, fileSystemId is: 0625e48855
                nas file system mount target is already created, mountTargetDomain is: 0625e48855-auv6.cn-hangzhou.nas.aliyuncs.com
        generated auto NasConfig done:  {"UserId":10003,"GroupId":10003,"MountPoints":[{"ServerAddr":"0625e48855-auv6.cn-hangzhou.nas.aliyuncs.com:/demo","MountDir":"/mnt/auto"}]}
        Checking if nas directories /demo exists, if not, it will be created automatically
        Checking nas directories done ["/demo"]
        Waiting for function demo to be deployed...
                Waiting for packaging function demo code...

Fun detected that your function demo/demo sizes exceed 50M. It is recommended that using the nas service to manage your function dependencies.
EISDIR: illegal operation on a directory, read
```
