### ISSUE TITLE
fun binary doesn't work in alpine

### ISSUE THREAD

**Issue by fujiwax** [alibaba/funcraft#999]
I've tried using fun in my .gitlab-ci.yml CICD pipeline, for which I've used alpine image. But apparently this doesn't work for me. It did work on debian:bullseye-slim image but I'd still prefer to use it in alpine.

This is what I had in .gitlab-ci.yml for test. This returns fun: Not found when I tried to check the version. 
```
deploy:
  stage: deploy
  image: alpine:latest
  scripts:
    - apk update
    - apk add curl unzip
    - curl -o fun-linux.zip https://gosspublic.alicdn.com/fun/fun-v3.6.14-linux.zip
    - unzip fun-linux.zip
    - mv fun-*-linux /usr/bin/fun
    - fun --version
```
